### ISSUE TITLE
JSON format for each MSRun

### ISSUE THREAD

**Issue by rolivella** [PRIDE-Archive/pride-metadata-standard#1]
I open this issue to discuss the MSRun JSON format. In this first draft we divided the JSON in two main parts: one with MSRun file metadata (filename, checksum, organism, instrument, etc.) and another one with the data itself. The "contextSource" allows to distinguish if the data is related either to the peptides inside the sample or to all the sample in general. We also follow the QC codes standards defined by the HUPO-PSI:

https://github.com/HUPO-PSI/qcML-development

In the latest specification of the HUPO-PSI, all the QC parameters that we have in our database are not yet defined, but we hope that they will be soon.

**Comment by ypriverol** [comment]
Can you provide us a version of the MSRun to start working with it.

**Comment by rolivella** [comment]
Yep, sorry. This is the first draft we are working with: 

```
{
    "file": {
        "checksum": "1a3cf866311505193b6b5d0044cd7927"
    },
    "data": [
        {
            "parameter": {"qCCV":"QC:1001844"},
            "values": [
                {
                    "contextSource": "TPAQFDADELR",
                    "value": "3333"
                },
                {
                    "contextSource": "HLVDEPQNLIK",
                    "value": "3223"
                }
            ]
        },
        {
            "parameter": {"qCCV":"QC:1000927"},
            "values": [
                {
                    "contextSource": "QC:1000927",
                    "value": "50"
                }
            ]
        }
    ]
}​ 
```

**Comment by ypriverol** [comment]
This is for the MSRun, But I was thinking to first are controlling general metadata such as Instrument, Fragmentation mode, etc.

**Comment by rolivella** [comment]
I was thinking to put this information in the "file", for instance: 

```
{
    "file": {
        "checksum": "1a3cf866311505193b6b5d0044cd7927",
        "mass_spec": "MS:1002732",
        "lc": "LC:0000003",
        "fragmentation_type": "CID" ,
        "filename": "20180621_01_01.raw"
    },

    "data": [
          ...
    ]
}​ 
```

**Comment by ypriverol** [comment]
Hi @rolivella we have a first prototype here: https://github.com/ypriverol/elixir-metadata-project/blob/master/technical-metadata/raw-file-metadata.json What do you think
